# Linux Build Pipeline
# Läuft parallel zu anderen Pipelines

labels:
  platform: linux/amd64

when:
  - event: push
  - event: pull_request
  - event: tag
  - event: manual

steps:
  - name: build-linux
    image: ubuntu:25.04
    commands:
      - echo "Workspace is $PWD"
      - export WORKSPACE="$PWD"
      - ls -la
      
      # Dependencies installieren
      - apt-get update
      - |
        apt-get install -y \
          autoconf automake libtool build-essential pkg-config curl ca-certificates \
          libevent-dev libboost-all-dev libssl-dev libzmq3-dev libminiupnpc-dev \
          libprotobuf-dev protobuf-compiler libqrencode-dev libsqlite3-dev \
          qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools qt6-svg-dev \
          qt6-l10n-tools \
          libqt6core5compat6-dev binutils ccache libdb-dev libdb++-dev libdb5.3++-dev \
          cmake git ninja-build libgmp-dev bsdextrautils || true
      
      # EVMC bauen
      - |
        cd /tmp
        git clone --recursive https://github.com/ethereum/evmc.git
        cd evmc && git checkout v12.1.0
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DEVMC_TESTING=OFF -DEVMC_TOOLS=OFF -DEVMC_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON
        make -j$(nproc) && make install
      
      # blst bauen
      - |
        cd /tmp
        git clone https://github.com/supranational/blst.git
        cd blst && git checkout v0.3.13
        ./build.sh
        cp libblst.a /usr/local/lib/
        cp bindings/blst.h bindings/blst_aux.h /usr/local/include/
      
      # evmone bauen
      - |
        cd /tmp
        git clone --recursive https://github.com/ethereum/evmone.git
        cd evmone && git checkout v0.18.0
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DEVMONE_TESTING=OFF -DEVMONE_FUZZING=OFF -DBUILD_SHARED_LIBS=ON
        make -j$(nproc) && make install
        ldconfig
      
      # pkg-config für EVMC erstellen
      - mkdir -p /usr/local/lib/pkgconfig
      - |
        cat > /usr/local/lib/pkgconfig/evmc.pc << 'EVMCPC'
        prefix=/usr/local
        exec_prefix=${prefix}
        libdir=${exec_prefix}/lib
        includedir=${prefix}/include
        Name: evmc
        Description: Ethereum Virtual Machine Connector
        Version: 12.1.0
        Libs: -L${libdir} -levmc-loader -levmc-instructions
        Cflags: -I${includedir}
        EVMCPC
      - |
        cat > /usr/local/lib/pkgconfig/evmone.pc << 'EVMONEPC'
        prefix=/usr/local
        exec_prefix=${prefix}
        libdir=${exec_prefix}/lib
        includedir=${prefix}/include
        Name: evmone
        Description: Fast Ethereum Virtual Machine implementation
        Version: 0.18.0
        Requires: evmc
        Libs: -L${libdir} -levmone
        Cflags: -I${includedir}
        EVMONEPC
      
      # Cascoin bauen (explizit im Workspace)
      - cd /woodpecker/src/codeberg.org/Cascoin/Cascoin && ./autogen.sh
      - |
        cd /woodpecker/src/codeberg.org/Cascoin/Cascoin
        export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
        CFLAGS="-g" CXXFLAGS="-g" \
        MOC=/usr/lib/qt6/libexec/moc \
        UIC=/usr/lib/qt6/libexec/uic \
        RCC=/usr/lib/qt6/libexec/rcc \
        LRELEASE=$(command -v lrelease || command -v lrelease-qt6 || echo /usr/lib/qt6/libexec/lrelease) \
        LUPDATE=$(command -v lupdate || command -v lupdate-qt6 || echo /usr/lib/qt6/libexec/lupdate) \
        ./configure \
          --with-gui=qt6 \
          --with-boost=/usr \
          --with-boost-libdir=/usr/lib/x86_64-linux-gnu \
          --enable-wallet \
          --enable-evmc \
          --with-evmc=/usr/local \
          --with-evmone=/usr/local \
          --with-incompatible-bdb
      - cd /woodpecker/src/codeberg.org/Cascoin/Cascoin && make -j$(nproc)
      
      # Binaries strippen
      - |
        cd /woodpecker/src/codeberg.org/Cascoin/Cascoin
        for b in src/qt/*-qt src/*coind src/*coin-cli; do
          if [ -x "$b" ]; then
            echo "Processing $b"
            objcopy --only-keep-debug "$b" "$b.debug" || true
            strip --strip-unneeded "$b" || true
          fi
        done
      
      # Ergebnis anzeigen
      - cd /woodpecker/src/codeberg.org/Cascoin/Cascoin && ls -lah src/ || true
      - cd /woodpecker/src/codeberg.org/Cascoin/Cascoin && ls -lah src/qt/ || true
      - cd /woodpecker/src/codeberg.org/Cascoin/Cascoin && file src/qt/*-qt || true
