name: Build Linux Distribution Package

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build-linux-distribution:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential autoconf automake libtool pkg-config \
          qt6-base-dev qt6-base-dev-tools qt6-tools-dev-tools \
          libprotobuf-dev protobuf-compiler \
          libevent-dev libboost-all-dev \
          libminiupnpc-dev libssl-dev libzmq3-dev libqrencode-dev \
          libdb++-dev patchelf chrpath

    - name: Build Cascoin Core
      run: |
        ./autogen.sh
        ./configure \
          --with-gui=qt6 \
          --enable-wallet \
          --with-qrencode \
          --enable-zmq \
          --with-incompatible-bdb \
          --prefix=/usr \
          MOC=/usr/lib/qt6/libexec/moc \
          UIC=/usr/lib/qt6/libexec/uic \
          RCC=/usr/lib/qt6/libexec/rcc \
          LRELEASE=/usr/bin/lrelease \
          LUPDATE=/usr/bin/lupdate
        make -j$(nproc)

    - name: Create distribution structure
      run: |
        # Create the directory structure
        mkdir -p cascoin-linux-distribution/usr/bin
        mkdir -p cascoin-linux-distribution/usr/lib/x86_64-linux-gnu
        mkdir -p cascoin-linux-distribution/usr/share/applications
        mkdir -p cascoin-linux-distribution/usr/share/pixmaps
        mkdir -p cascoin-linux-distribution/usr/share/man/man1
        mkdir -p cascoin-linux-distribution/usr/lib/qt6/plugins
        mkdir -p cascoin-linux-distribution/etc/ld.so.conf.d
        
        # Copy binaries
        cp src/qt/cascoin-qt cascoin-linux-distribution/usr/bin/
        cp src/cascoind cascoin-linux-distribution/usr/bin/
        cp src/cascoin-cli cascoin-linux-distribution/usr/bin/
        cp src/cascoin-tx cascoin-linux-distribution/usr/bin/
        
        # Strip binaries to reduce size
        strip cascoin-linux-distribution/usr/bin/*

    - name: Copy required libraries
      run: |
        # Function to copy library and its dependencies recursively
        copy_lib_recursive() {
            local lib_path="$1"
            local dest_dir="$2"
            
            if [[ -f "$lib_path" ]]; then
                # Copy the library itself
                cp "$lib_path" "$dest_dir/"
                echo "Copied: $lib_path"
                
                # Get dependencies and copy them too
                ldd "$lib_path" 2>/dev/null | grep "=>" | awk '{print $3}' | while read dep; do
                    if [[ -f "$dep" && "$dep" =~ ^/usr/lib|^/lib ]]; then
                        local dep_name=$(basename "$dep")
                        if [[ ! -f "$dest_dir/$dep_name" ]]; then
                            copy_lib_recursive "$dep" "$dest_dir"
                        fi
                    fi
                done
            fi
        }
        
        LIB_DIR="cascoin-linux-distribution/usr/lib/x86_64-linux-gnu"
        
        # Get all library dependencies for each binary
        for binary in cascoin-linux-distribution/usr/bin/*; do
            echo "Analyzing dependencies for: $binary"
            ldd "$binary" 2>/dev/null | grep "=>" | awk '{print $3}' | while read lib; do
                if [[ -f "$lib" && "$lib" =~ ^/usr/lib|^/lib ]]; then
                    lib_name=$(basename "$lib")
                    if [[ ! -f "$LIB_DIR/$lib_name" ]]; then
                        copy_lib_recursive "$lib" "$LIB_DIR"
                    fi
                fi
            done
        done
        
        # Copy Qt6 specific libraries and plugins
        echo "Copying Qt6 libraries..."
        find /usr/lib/x86_64-linux-gnu -name "libQt6*.so*" -exec cp {} "$LIB_DIR/" \;
        
        # Copy Qt6 plugins
        echo "Copying Qt6 plugins..."
        if [[ -d /usr/lib/x86_64-linux-gnu/qt6/plugins ]]; then
            cp -r /usr/lib/x86_64-linux-gnu/qt6/plugins/* cascoin-linux-distribution/usr/lib/qt6/plugins/
        fi
        
        # Copy essential system libraries
        echo "Copying essential system libraries..."
        essential_libs=(
            "libssl.so*"
            "libcrypto.so*"
            "libboost_*.so*"
            "libevent*.so*"
            "libprotobuf.so*"
            "libminiupnpc.so*"
            "libzmq.so*"
            "libqrencode.so*"
            "libdb*.so*"
            "libstdc++.so*"
            "libgcc_s.so*"
            "libpthread.so*"
            "libc.so*"
            "libm.so*"
            "libdl.so*"
            "librt.so*"
        )
        
        for pattern in "${essential_libs[@]}"; do
            find /usr/lib/x86_64-linux-gnu /lib/x86_64-linux-gnu -name "$pattern" 2>/dev/null | while read lib; do
                if [[ -f "$lib" ]]; then
                    cp "$lib" "$LIB_DIR/" 2>/dev/null || true
                fi
            done
        done

    - name: Create desktop entry and wrapper scripts
      run: |
        # Create desktop entry
        cat > cascoin-linux-distribution/usr/share/applications/cascoin-qt.desktop << 'EOF'
        [Desktop Entry]
        Name=Cascoin Core
        Comment=Cascoin cryptocurrency wallet
        Icon=cascoin
        Exec=/usr/bin/cascoin-qt-wrapper
        Terminal=false
        Type=Application
        Categories=Office;Finance;
        StartupWMClass=Cascoin-qt
        EOF
        
        # Copy icon if available
        if [[ -f share/pixmaps/bitcoin128.png ]]; then
            cp share/pixmaps/bitcoin128.png cascoin-linux-distribution/usr/share/pixmaps/cascoin.png
        fi
        
        # Create wrapper script for cascoin-qt to set library paths
        cat > cascoin-linux-distribution/usr/bin/cascoin-qt-wrapper << 'EOF'
        #!/bin/bash
        export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
        export QT_PLUGIN_PATH="/usr/lib/qt6/plugins:$QT_PLUGIN_PATH"
        exec /usr/bin/cascoin-qt "$@"
        EOF
        chmod +x cascoin-linux-distribution/usr/bin/cascoin-qt-wrapper
        
        # Create wrapper script for cascoind
        cat > cascoin-linux-distribution/usr/bin/cascoind-wrapper << 'EOF'
        #!/bin/bash
        export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
        exec /usr/bin/cascoind "$@"
        EOF
        chmod +x cascoin-linux-distribution/usr/bin/cascoind-wrapper

    - name: Create installation script
      run: |
        cat > cascoin-linux-distribution/install.sh << 'EOF'
        #!/bin/bash
        
        if [[ $EUID -ne 0 ]]; then
           echo "This script must be run as root (use sudo)"
           exit 1
        fi
        
        echo "Installing Cascoin Core Linux Distribution..."
        
        # Copy all files to system directories
        cp -r usr/* /usr/
        
        # Update library cache
        echo "/usr/lib/x86_64-linux-gnu" > /etc/ld.so.conf.d/cascoin.conf
        ldconfig
        
        # Update desktop database
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database
        fi
        
        echo "Installation complete!"
        echo ""
        echo "You can now run:"
        echo "  cascoin-qt-wrapper    # GUI wallet"
        echo "  cascoind-wrapper      # Daemon"
        echo "  cascoin-cli           # CLI tool"
        echo "  cascoin-tx            # Transaction tool"
        echo ""
        echo "Or use the desktop entry: Cascoin Core"
        EOF
        chmod +x cascoin-linux-distribution/install.sh
        
        # Create uninstall script
        cat > cascoin-linux-distribution/uninstall.sh << 'EOF'
        #!/bin/bash
        
        if [[ $EUID -ne 0 ]]; then
           echo "This script must be run as root (use sudo)"
           exit 1
        fi
        
        echo "Uninstalling Cascoin Core..."
        
        # Remove binaries
        rm -f /usr/bin/cascoin-qt
        rm -f /usr/bin/cascoind
        rm -f /usr/bin/cascoin-cli
        rm -f /usr/bin/cascoin-tx
        rm -f /usr/bin/cascoin-qt-wrapper
        rm -f /usr/bin/cascoind-wrapper
        
        # Remove desktop entry
        rm -f /usr/share/applications/cascoin-qt.desktop
        rm -f /usr/share/pixmaps/cascoin.png
        
        # Remove library config
        rm -f /etc/ld.so.conf.d/cascoin.conf
        ldconfig
        
        # Update desktop database
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database
        fi
        
        echo "Uninstallation complete!"
        EOF
        chmod +x cascoin-linux-distribution/uninstall.sh

    - name: Create README for distribution
      run: |
        cat > cascoin-linux-distribution/README.md << 'EOF'
        # Cascoin Core Linux Distribution Package
        
        This package contains a complete, self-contained installation of Cascoin Core
        with all required libraries included. No additional package installation required.
        
        ## Contents
        
        - **cascoin-qt**: GUI wallet application
        - **cascoind**: Daemon/server
        - **cascoin-cli**: Command-line interface
        - **cascoin-tx**: Transaction utility
        - **All required libraries**: Qt6, Boost, OpenSSL, etc.
        
        ## Installation
        
        ```bash
        sudo ./install.sh
        ```
        
        ## Usage
        
        After installation, you can run:
        
        ```bash
        cascoin-qt-wrapper    # GUI wallet
        cascoind-wrapper      # Daemon
        cascoin-cli           # CLI tool
        cascoin-tx            # Transaction tool
        ```
        
        Or use the desktop entry "Cascoin Core" from your application menu.
        
        ## Manual Installation
        
        If you prefer manual installation:
        
        ```bash
        sudo cp -r usr/* /usr/
        sudo echo "/usr/lib/x86_64-linux-gnu" > /etc/ld.so.conf.d/cascoin.conf
        sudo ldconfig
        ```
        
        ## Uninstallation
        
        ```bash
        sudo ./uninstall.sh
        ```
        
        ## System Requirements
        
        - Linux x86_64
        - GLIBC 2.31+ (Ubuntu 20.04+, similar for other distributions)
        - X11 or Wayland display server (for GUI)
        
        ## Build Information
        
        Built with:
        - Qt6 GUI framework
        - Berkeley DB wallet support
        - ZMQ support
        - QR code support
        - UPnP support
        
        ## Support
        
        For support and documentation, visit: https://github.com/cascoin/cascoin
        EOF

    - name: Package distribution
      run: |
        # Create version info
        VERSION=$(git describe --tags --always --dirty)
        echo "Building version: $VERSION"
        
        # Create tarball
        tar -czf "cascoin-linux-x86_64-$VERSION.tar.gz" cascoin-linux-distribution/
        
        # Create detailed file list
        find cascoin-linux-distribution -type f -exec ls -la {} \; > "cascoin-linux-x86_64-$VERSION-filelist.txt"
        
        # Show package info
        echo "Package contents:"
        ls -la cascoin-linux-x86_64-*

    - name: Upload distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: cascoin-linux-x86_64-distribution
        path: |
          cascoin-linux-x86_64-*.tar.gz
          cascoin-linux-x86_64-*-filelist.txt
        retention-days: 30

    - name: Upload to release (if release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./cascoin-linux-x86_64-${{ github.event.release.tag_name }}.tar.gz
        asset_name: cascoin-linux-x86_64-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip
